# Generated by Django 5.2 on 2025-05-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataFileUpload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=50)),
                ("actual_file", models.FileField(upload_to="uploads/")),
                (
                    "description",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
            ],
        ),
    ]
